apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sonar-cert
spec:
  commonName: sonar.cmays-lab.com
  secretName: sonar-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
